### ISSUE TITLE
Can't pass null to syscall

### ISSUE THREAD

**Issue by amigrave** [def-/nim-syscall#1]
I'd like to call `splice` syscall and pass NULL but can't find a way to do so, eg:

```nim
result = syscall(SPLICE, fd_in, nil, fd_out, nil, length, SPLICE_FLAGS)
```

http://man7.org/linux/man-pages/man2/splice.2.html

**Comment by def-** [comment]
It seems to compile to me. What is the problem exactly?

**Comment by amigrave** [comment]
Hi @def- ,

I'm sorry, my mistake was in the usage of splice, nothing to do with syscall. (I was not using a pipe in between the two file descriptors). Everything is running well now that I'm using splice properly.

Please accept my apologies for the noise.
